[package]
name = "gdb-server"
version = "0.11.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>", "Dominik Boehi <dominik.boehi@gmail.ch>"]
edition = "2018"
description = "A gdb stub implementation for on chip debugging and flashing of ARM chips."
documentation = "https://docs.rs/probe-rs-cli/"
homepage = "https://github.com/probe-rs/probe-rs"
repository = "https://github.com/probe-rs/probe-rs"
readme = "../README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[lib]
name = "probe_rs_gdb_server"
path = "src/lib.rs"

[[bin]]
name = "gdb-server"
path = "src/bin.rs"
required-features = ["build-binary"]

[features]
build-binary = ["pretty_env_logger", "structopt", "colored"]
ftdi = ["probe-rs/ftdi"]

[dependencies]
pretty_env_logger = { version = "0.4.0", optional = true }
structopt = { version = "0.3.2", optional = true }
colored = { version = "2.0.0", optional = true }
probe-rs = { path = "../probe-rs", version = "0.11.0" }
gdb-protocol = { version = "0.1.0" }
async-std = { version = "1.7.0" }
futures = "0.3.1"
log = "0.4.0"
memchr = "2.3.4"
hex = "0.4.2"
nom = "=7.1.0"
anyhow = "1.0.31"
